### PR TITLE
Fix Repo Owner

### LINKED ISSUE #10: Github Organizations not Supported
Badger is not able to update the PR description on a repository within a Github organization. No errors are flagged however the logs show a `404 Not Found` response from the Github API when it tries to send the update.

### PR DESCRIPTION
**Pull request by StevenMilneDev**
This branch fixes #10 where organisations were not supported. This turned out to be a mistake in the API call where the `owner` property was set to the PR owner, this is wrong it should be the repo owner. This means that the action would only work on PRs from the repository owner.

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -1,27 +1,21 @@
...
+import { getInput, info, warning, error, setFailed } from '@actions/core'
 import { getOctokit, context } from '@actions/github'
+import { Context } from '@actions/github/lib/context'
 import * as github from './util/github'
 import Badge from './util/badge'
 import _ from 'lodash'
 import Resolver from './Resolver'
 
 const token = getInput('token')
+const isDebug = getInput('debug') === 'true'
```
Comment (StevenMilneDev) [inline src/index.ts:10]: I should maybe import `isDebug` from `@actions/core` and using that 🤔

File: src/index.ts [hunk 2]
```diff
@@ -1,27 +1,21 @@
...
-} else if (!token) {
-  error(`Authentication token not provided.`)
-} else {
-  const resolver = new Resolver(context)
-
-  const body = context.payload.pull_request.body
-  const prefix = getInput('prefix')
-  const suffix = getInput('suffix')
+if (isDebug) {
+  console.log(`********************************\nGitHub Context\n\n${JSON.stringify(context)}\n\n********************************`)
```
Comment (StevenMilneDev) [inline src/index.ts:13]: Could just import `debug` from `@actions/core` and use that for automatic `isDebug` coverage 😁
